### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by nopper** [marcocor/bing-api-java#1]
Hi Marco,

Are you planning to deploy the library on Maven Central? Thank you for such wonderful library.

**Comment by marcocor** [comment]
Hi nopper,
thank you for your comment. I am right in the middle of the process of publishing this library in the Maven Central Repository. Just a few days before my new-project request get handled by Sonatype. So excited ^.^

**Comment by nopper** [comment]
That's amazing. Keep up the good work :+1: 

Closing the issue
